---
- block:
  - name: Login to oVirt engine
    ovirt_auth:
      username: "{{ engine_user | default(omit) }}"
      password: "{{ engine_password | default(omit) }}"
      url: "{{ (engine_fqdn is defined) | ternary('https://' ~engine_fqdn~ '/ovirt-engine/api', omit) }}"
      ca_file: "{{ engine_cafile | default(omit) }}"
      insecure: "{{ engine_cafile is undefined }}"
    tags:
      - always

  - name: Deploy qcow disk
    include_tasks: deploy_qcow2.yml

  - block:
    - name: Create ManageIQ virtual machine
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: present
        name: "{{ miq_vm_name }}"
        cluster: "{{ miq_vm_cluster }}"
        memory: "{{ miq_vm_memory }}"
        cpu_cores: "{{ miq_vm_cpu }}"
        operating_system: "{{ miq_vm_os }}"
        type: server
        disks:
          - id: "{{ ovirt_disk.id }}"
            bootable: true
        nics: "{{ miq_vm_nics }}"
      register: create_vm

    - name: Duplicate miq_init_cmd variable to override it
      set_fact:
        miq_init_cmd2: "{{ miq_init_cmd }}"

    - include_tasks: cfme_identify_disk_device.yml

    - include_tasks: cfme_add_disk.yml
      when: "item in miq_vm_disks"
      with_items: "{{ miq_vm_disks_types }}"

    - name: Ensure virtual machine is running
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: running
        name: "{{ miq_vm_name }}"
        cloud_init: "{{ miq_vm_cloud_init | default(omit) }}"

    - name: Wait for VM IP
      ovirt_vms_facts:
        auth: "{{ ovirt_auth }}"
        pattern: "name={{ miq_vm_name }}"
        fetch_nested: true
        nested_attributes: ips
      until: ovirt_vms | map(attribute='reported_devices') | list | first | length > 0
      retries: 10
      delay: 10

    - name: ManageIQ host IP address
      set_fact:
        miq_ip_addr: "{{ ovirt_vms | ovirtvmipv4 }}"

    - block:
      - include: init_cfme.yml
      - include: wait_for_api.yml

      when: "miq_initialize"
    when: "not miq_disk_deploy_failed"

  always:
    - name: Logout from oVirt engine
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
